<?php

namespace HimaMage\ExampleCommand\Console\Command;

use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Input\InputOption;
use Symfony\Component\Console\Output\OutputInterface;

class ExampleCommand extends  Command
{
    protected function configure()
    {
        parent::configure(); // TODO: Change the autogenerated stub
        $this->setName('himamage:example:run');
        $this->setDescription('this is training command');

        // arguments
//        $this->addArgument('first_name' , InputArgument::REQUIRED);
//        $this->addArgument('grades' , InputArgument::REQUIRED | InputArgument::IS_ARRAY);

        // options
        $this->addOption('is_student' , null , InputOption::VALUE_NONE);

    }

    protected function execute(InputInterface $input, OutputInterface $output)
    {
//        $first_name = $input->getArgument('first_name');
//        $grades= $input->getArgument('grades');
//        $output->writeln('first name ' . $first_name);
//        $output->writeln($grades);

        $is_student = $input->getOption('is_student');
        $output->writeln($is_student);

    }

}
